# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'KYAsyncLoadBubbleDemo' do

platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"

end

target 'KYAsyncLoadBubbleDemoTests' do

end

